export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const UPDATE_ACTOR_SUGGESTIONS = 'UPDATE_ACTOR_SUGGESTIONS';
export const CLEAR_ACTOR_SUGGESTIONS = 'CLEAR_ACTOR_SUGGESTIONS';
export const UPDATE_MOVIE_DATA = 'UPDATE_MOVIE_DATA';
